#!/bin/sh -x

FEATURE=$1
CURRENT=`git branch | grep "*" | awk '{print $2}'`
USER=cmilfont
URL="https://api.github.com/repos/fortesinformatica/forteschat3/issues/${FEATURE}/comments"

git checkout $CURRENT
git pull --rebase origin $CURRENT
git checkout -b $1 $CURRENT

curl -v -H "Accept: application/json" -H "Content-type: application/json" -u "{USER} -d '{"body":"Starting"}' $URL
