#!/bin/sh -x

if [ $# -ne 1 ]; then
         echo 1>&2 Usage: $0 branch_name
         exit 127
fi
branch_name=$1
git checkout master
git branch -D $branch_name
git push origin master:$branch_name
#git push origin origin:refs/heads/$branch_name
git fetch origin
git branch -r
git checkout --track -b $branch_name origin/$branch_name
git pull
